### PR TITLE
Few fixes

### PR DESCRIPTION
**Pull request by ddk85**

### CODE REVIEW

**Comment by giddie** [comment]
Could you explain the purpose of the script?

**Comment by ddk85** [comment]
If "interactive_assignment" didn't checked - you coldn't check
"self_assignment".
Maybe it's too much complexity...

2015-11-19 14:45 GMT+03:00 Paul Gideon Dann <notifications@github.com>:

**Comment by giddie** [comment]
I think they're separate features; is there a link between self_assignment and interactive_assignment that I haven't thought of? I think it would still be useful to be able to set self_assignment if interactive_assignment is disabled.

**Comment by ddk85** [comment]
The link is in code :)))
In default_assign_issues_hooks.rbat line 10:
return if not interactive_assignment

So it doen't work if only self_assignment checked :)

I think that you are right and functions could be used separatly, but we
need to make changes in code.

2015-11-19 14:58 GMT+03:00 Paul Gideon Dann <notifications@github.com>:

**Comment by giddie** [comment]
I tested the functionality before pushing, and I think it already behaves correctly. The method in `default_assign_issues_hooks` is called as the issue form is rendered (or re-rendered via AJAX), so it affects what is visible on the form before it is submitted. This is the functionality that is switched off when `interactive_assignment` is switched off.

However, in the `default_assign_issue_patch` file, you'll find the method that is called when the form is submitted. This logic is applied regardless of whether `interactive_assignment` is set or not. This is the part of the plugin that sets an assignee if one was not selected on the form.

**Comment by giddie** [comment]
I'm going to close this, but feel free to re-open if you think I missed something.

**Pull request closed without merging**
