### PR TITLE
Self assignment

### PR DESCRIPTION
**Pull request by giddie**

### CODE REVIEW

**Comment by ddk85** [comment]
At "settings :default =>" in init.rb didn't need specify the variable "'self_assignment' => false"?

Also I will do few changes in Russian translation....as soon understand how :))))

**Comment by giddie** [comment]
Yes, you're right: I've now added the default value to the hash in init.rb :)

**Comment by ddk85** [comment]
Ops...
My fail - added as #26

**Comment by giddie** [comment]
I've added your Russian translation to this branch. Any further tweaks required before I merge?

**Pull request merged**
