### PR TITLE
Add author_url for easy search. Also mod default_assign_issues_hooks …

### PR DESCRIPTION
**Pull request by ddk85**
…- if no default assigne selected - assign to "myself"

### CODE REVIEW

**Comment by giddie** [comment]
Can you remember what the default behaviour is if the assignee field is left blank without this plugin? I think it leaves the assignee blank, doesn't it? If so, we shouldn't really change that behaviour, I think.

**Comment by ddk85** [comment]
Yes, it's blank. In some projects it may be usefull to change it, maybe in
some not.
If it possible to do it via plugin configuration - maybe it'll be more
correct.

2015-11-17 15:58 GMT+03:00 Paul Gideon Dann <notifications@github.com>:

**Comment by giddie** [comment]
Yes, it could make sense to have a "self" option as a global default option in the plugin settings. If you could implement that, I'd be happy to merge that feature :)

**Comment by ddk85** [comment]
Almost did it :)
Only one thing I doesn't know how to realize - how to disable new "self"
checkbox if "interactive" checkbox not selected.

2015-11-17 16:16 GMT+03:00 Paul Gideon Dann <notifications@github.com>:

**Comment by giddie** [comment]
OK, good. You've accidentally committed some old code in there, so I've put together a new commit, incorporating your work along with some minor modifications of my own. Can you have a look and comment on #25?

**Comment by giddie** [comment]
I'll close this pull request for now, as the required feature should be handled in #25.

**Pull request closed without merging**
